# -*- coding: utf-8 -*-
"""my_fun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHNIcjP11FbviGXDtRbVWWTcDymvCY9i
"""

# Commented out IPython magic to ensure Python compatibility.
def git_push(file_name):# ⚙️ 필요한 설정값
  GITHUB_USERNAME = "yujinc129-oss"
  GITHUB_EMAIL = "yujinc129@gmail.com"
  GITHUB_REPO = "Drama_data_project"
  GITHUB_FOLDER = "data/processed"
  GITHUB_BRANCH = "main"  # 보통은 main
  COMMIT_MSG = "Add final CSV from Colab"


  FILENAME = file_name  # 저장할 파일 이름


  # 🛠️ Git 설치 및 기본 설정
  !git config --global user.email "{GITHUB_EMAIL}"
  !git config --global user.name "{GITHUB_USERNAME}"

  # 🔄 저장소 클론
  !git clone https://github.com/{GITHUB_USERNAME}/{GITHUB_REPO}.git
#   %cd {GITHUB_REPO}

  # 📁 저장소 내부의 저장 폴더로 이동
  import shutil
  shutil.move(f"/content/{FILENAME}", f"{GITHUB_FOLDER}/{FILENAME}")

  # 📝 파일 git에 추가하고 커밋
  !git add {GITHUB_FOLDER}/{FILENAME}
  !git commit -m "{COMMIT_MSG}"

  !git push https://yujinc129-oss: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@github.com/yujinc129-oss/Drama_data_project.git